### ISSUE TITLE
HasParam check failed

### ISSUE THREAD

**Issue by jocacace** [tuloski/swm_ros_interface#1]
Ros parameter server matain the parmiters stored in the launch file even thought they are deleted.

HasParam cannot be used, anyway to change the publisher/subscriber to/from the swm the roscore must be restart. 
As suggestion we can consider the value of a param

**Comment by tuloski** [comment]
Is this a problem? When you stop the screen, the master is gone and the parameters also.
I think reading the value of the param has the same problem, unless every .launch file has all the parameters and put at false the pub/sub list it doesn't need.
